# Generated by Django 4.1.4 on 2022-12-19 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_immobile_is_locate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmobileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images', verbose_name='Images')),
                ('immobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immobile_images', to='myapp.immobile')),
            ],
        ),
    ]
