# Generated by Django 4.1.4 on 2022-12-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_immobileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerlocation',
            name='date_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='immobile',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
