# Generated by Django 4.1.4 on 2022-12-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_registerlocation_date_at_alter_immobile_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerlocation',
            name='date_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
