# Generated by Django 4.1.4 on 2022-12-20 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_registerlocation_date_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerlocation',
            name='date_at',
        ),
        migrations.AddField(
            model_name='registerlocation',
            name='create_at',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
