# Generated by Django 4.1.4 on 2022-12-20 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_registerlocation_date_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerlocation',
            name='immobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_location', to='myapp.immobile'),
        ),
    ]
